#!/usr/bin/env bash
#
# Summary: Setup a package, install bin, man, source and completion
# Usage: basher setup <package>
#
# Install a existing package

set -e

if [ "$#" -ne 1 ]; then
  basher-help setup
  exit 1
fi  
    
if [[ "$1" = */*/* ]]; then
  IFS=/ read -r site user name <<< "$1"
  package="${user}/${name}"
else
  package="$1"
  site="github.com"
fi

#IFS=/ read -r user name <<< "$package"

if [[ ! -d "${BASHER_PACKAGES_PATH}/$package" ]] ; then
  echo "Package '$package' must be already installed, please use '${0##*/} [install|link]' before"
  exit 1
fi

basher-_deps "$package"
basher-_link-bins "$package"
basher-_link-man "$package"
basher-_link-completions "$package"
basher-_link-sources "$package"    


>&2 echo "Package '$package' installed"
